#!/bin/sh

kver="$(rpm -qa 'kernel-image*' \
	    --qf '%{installtime} %{version}-%{name}-%{release}\n' \
	| sort -n \
	| tail -n 1 \
	| cut -f 2 -d ' ' \
	| sed 's/kernel-image-//')"

[ -h /boot/vmlinuz ] || ln -s vmlinuz-$kver /boot/vmlinuz
[ -h /boot/initrd.img ] || ln -s initrd-$kver.img /boot/initrd.img

# NB: mkinitrd-3.0.16+ has rootsubdir support which is critical
#     for TWRP based ARM "VE" chroots (e.g. for nexus7);
#     should be implemented in make-initrd either

if rpm -q mkinitrd; then
	mkinitrd --with ext4 -f /boot/initrd-$kver.img "$kver"
fi

:
