#!/bin/sh

[ -n "$GLOBAL_GNOME_KB_SWITCH" ] || exit 0

gsettings get org.gnome.desktop.wm.keybindings switch-input-source || return 0

cat > /etc/dconf/db/local.d/01-gnome-keymap <<EOF
[org/gnome/desktop/wm/keybindings]
switch-input-source=['`echo $GLOBAL_GNOME_KB_SWITCH`', '<Super>space', 'XF86Keyboard']
EOF
