#!/bin/sh
# partial port of livecd-setlocale (kbd bits)

CONFIG=/etc/sysconfig/keyboard
VCONSOLE_CONF=/etc/vconsole.conf

[ -n "$GLOBAL_KEYTABLE" ] || exit 0

# Requires: console-scripts
if [ -s "$CONFIG" ]; then
	echo "KEYTABLE=$GLOBAL_KEYTABLE" > "$CONFIG"
fi

rpm -qf "$VCONSOLE_CONF" && echo "KEYMAP=$GLOBAL_KEYTABLE" >> "$VCONSOLE_CONF"
:
