#!/bin/sh
# see also m-p-d::profiles/live/image-scripts.d/init3-services

#[ -x /bin/systemctl ] || exit 0
#[ -x /bin/systemctl ] || exit 0

ENABLE="
network
NetworkManager
lvm2-monitor
mdadm
"

# NB: dnsmasq: https://bugzilla.altlinux.org/show_bug.cgi?id=18799
# NB: sshd might be needed for some particular cases
DISABLE="
sshd
"

for i in $ENABLE;  do
	[ -x /bin/systemctl ] && /bin/systemctl --no-reload enable ${i}.service
	[ -x /sbin/chkconfig ] && /sbin/chkconfig $i on
done

for i in $DISABLE; do
	[ -x /bin/systemctl ] && /bin/systemctl --no-reload disable ${i}.service
	[ -x /sbin/chkconfig ] && /sbin/chkconfig $i off
done
:
