#!/bin/sh
# see also m-p-d::profiles/live/image-scripts.d/init3-services

ENABLE="
livecd-setlocale
livecd-evms
livecd-save-nfs
livecd-timezone
"

DISABLE="
"

for i in $ENABLE;  do
	/bin/systemctl --no-reload enable "$i" ||:
done

for i in $DISABLE; do
	/bin/systemctl --no-reload disable "$i" ||:
done
:
