#!/bin/sh
# setup control(8) states for the installed system

[ -n "$GLOBAL_CONTROL" ] || exit 0
[ -x /usr/sbin/install2 ] || [ -x /usr/libexec/install2/install2 ] || exit 0
echo "$GLOBAL_CONTROL" | tr ' :' '\n ' > /usr/share/install2/control
