#!/bin/sh -efu
# remove temporary packages from the installed system

### FIXME: need to proxy CLEANUP_PACKAGES -> GLOBAL_CLEANUP_PACKAGES somewhere
list="$(rpmquery -a --qf='%{NAME}\n' $GLOBAL_CLEANUP_PACKAGES)"
[ -z "$list" ] || apt-get remove -f -y  -- $list
