#!/bin/sh

mkdir -p "$WORKDIR"/syslinux
MEMTEST="$(find /boot/ -name 'memtest*' -print -quit)"
# hdt wiki recommends adding .bin
[ -z "$MEMTEST" ] ||
	cp -f "$MEMTEST" "$WORKDIR"/syslinux/memtest.bin
