#!/bin/sh
# Run scripts from /etc/firsttime.d at first start
[ -d /etc/firsttime.d ] || exit 0
[ "$(ls /etc/firsttime.d 2>/dev/null |wc -l)" != 0 ] || exit 0
[ -f /etc/firsttime.flag ] || touch /etc/firsttime.flag
