#!/bin/sh

# don't cripple the image to be copied over
[ -x /usr/sbin/live-install -o -x /usr/sbin/livecd-install ] && exit 0

# remove unused fonts
cd /usr/share/fonts/bitmap/misc/ &&
	rm -f *ja.* *ko.* han* gb* jis* k14* rk* *rk.* *kana* cl* *JIS*

# drop unneeded translations
cd /usr/share/qt?/translations/ && rm -f *_zh* *_ja*

# l10n
cd /usr/share/X11/locale && rm -rf ja* ko* th* vi* zh*

# xkb
cd /usr/share/X11/xkb/symbols && rm -rf jp kr th vn cn

# locales
cd /usr/lib/locale && rm -rf ja_* ko_* th_* zh_*

# gconv
cd /usr/lib*/gconv && rm -f JIS* T*

:
