#!/bin/sh

# don't cripple the image to be copied over
[ -x /usr/sbin/live-install -o -x /usr/sbin/livecd-install ] && exit 0

# remove unused legacy/tiny fonts
#cd /usr/share/fonts/bitmap/misc/ && rm -f *ISO* *KOI* [1456]*
cd /usr/share/fonts/bitmap/misc/ && rm -f [1456]*

# l10n
cd /usr/share/X11/locale/ && rm -rf *[^C8]/ iso*

# xkb
cd /usr/share/X11/xkb/symbols && rm -rf *_vndr

# gconv
#cd /usr/lib*/gconv && rm -f CP* ISO* *JIS* KOI* HP* MAC*
cd /usr/lib*/gconv && rm -f CP* *JIS* HP* MAC*

:
