#!/bin/sh

# don't cripple the image to be copied over
[ -x /usr/sbin/live-install -o -x /usr/sbin/livecd-install -o \
  -x /usr/sbin/homeros-install -o -x /usr/sbin/luwrain-install ] && exit 0

# no need for the kernel in live root otherwise: it's been booted already
rm -f /boot/*

:
