#!/bin/sh

[ "$GLOBAL_BASE_BOOTLOADER" = 'uboot' ] || exit 0

if [ -n "$GLOBAL_TTY_RATE" ] ;then
	TTY="$GLOBAL_TTY_DEV","$GLOBAL_TTY_RATE"
else
	TTY="$GLOBAL_TTY_DEV"
fi

# installkernel relies on existing extlinux.conf
# with filled in `default' label
mkdir -p /boot/extlinux
cat > /boot/extlinux/extlinux.conf << EOF
menu title ALTLinux Boot Options

default linux
timeout 20

label linux
	kernel /boot/vmlinuz
	initrd /boot/initrd.img
	fdtdir /boot/dtb
	append root=LABEL=ROOT ro cma=192M console=$TTY
EOF
