#!/bin/sh -x

kver="$(rpm -qa 'kernel-image*' \
            --qf '%{installtime} %{version}-%{name}-%{release}\n' \
        | sort -n \
        | cut -f 2 -d ' ' \
        | sed 's/kernel-image-//')"

[ -n "$kver" ] || { echo "** unable to deduce kernel version" >&2; exit 1; }

for KVER in $kver; do
	/sbin/installkernel --uboot --keep-initrd "$KVER"
done
printf 'LABEL=ROOT\t/\text4\tdefaults\t1 1\n' >> /etc/fstab
