#!/bin/sh -x

[ -n "$GLOBAL_KFLAVOURS" ] ||
  { echo "** KFLAVOURS is empty" >&2; exit 0; }

kver=
for KFLAVOUR in $GLOBAL_KFLAVOURS; do
	kver+=" $(rpm -qa 'kernel-image*' \
		--qf '%{version}-%{name}-%{release}\n' \
	| grep "$KFLAVOUR" \
	| sed 's/kernel-image-//')"
done
[ ! -z "${kver#"${kver%%[! ]*}"}" ] ||
  { echo "** unable to deduce kernel version" >&2; exit 1; }

for KVER in $kver; do
	/sbin/installkernel --uboot --keep-initrd "$KVER"
done
