#!/bin/sh

if [ -n "$GLOBAL_ROOTPW" ]; then
	if type -t chpasswd >&/dev/null; then
		echo "root:$GLOBAL_ROOTPW" | chpasswd
	else
		echo "** warning: chpasswd binary missing" >&2
	fi
else
	echo "** warning: no root password provided, you're on your own" >&2
fi
