#!/bin/sh
# predictable file locations make bootloader configuration simple;
# this script relates to features.in/stage2/stage1/scripts.d/81-make-initfs

kver="$(rpm -qa 'kernel-image*' \
            --qf '%{installtime} %{version}-%{name}-%{release}\n' \
        | sort -n \
        | tail -n 1 \
        | cut -f 2 -d ' ' \
        | sed 's/kernel-image-//')"

[ -n "$kver" ] || { echo "** unable to deduce kernel version" >&2; exit 1; }

cd /boot
echo "$kver" > .origver	# for tar2fs

# NB: e2k kernel builds "image" instead of "vmlinuz"
[ -f vmlinuz-$kver ] && ln -s vmlinuz-$kver vmlinuz ||:
ln -s initrd-$kver.img initrd.img	# missing at this stage
:
