#!/bin/sh -efu

mkdir -p /root/.install-log
cd /root/.install-log
rpm -qa --qf '%{name}-%{version}-%{release}.%{arch}.rpm\n' | sort -u > rpm.txt
rpm -qa --qf '%{sourcerpm}\n' | sed 's/^i586-//' | sort -u > srpm.txt
