#!/bin/sh -eu

if [ -n "${GLOBAL_BASE_BOOTARGS-}" ]; then
    if [ -s /etc/sysconfig/grub2 ]; then
        sed -Ei \
            "s/(GRUB_CMDLINE_LINUX_DEFAULT=)(.*)(['\"])/\1\2 $GLOBAL_BASE_BOOTARGS\3/" \
            /etc/sysconfig/grub2
    fi
fi
