#!/bin/sh
# Install /etc/*-release files if needed
rel_file=
for rel_file in altlinux-release os-release; do
	if ! [ -e /etc/"$rel_file" ]; then
		# in case it is dangling symlink
		rm -f /etc/"$rel_file"
		if [ -r /usr/share/branding-data-current/release/"$rel_file" ]; then
			cp -at /etc -- \
				/usr/share/branding-data-current/release/"$rel_file"
						elif [ -r /usr/lib/"$rel_file" ]; then
							cp -a /usr/lib/"$rel_file" /etc/"$rel_file"
		fi
	fi
done
