#!/bin/sh
# Install /etc/*-release files if needed
if [ -d /usr/share/branding-data-current ]; then
	local rel_file=
	for rel_file in altlinux-release os-release; do
		if ! [ -e /etc/"$rel_file" ]; then
			# in case it is dangling symlink
			rm -f /etc/"$rel_file"
			cp -at /etc -- \
				/usr/share/branding-data-current/release/"$rel_file"
		fi
	done
fi
