#!/bin/sh -efu
# NB: keyboard layout not included!

if [ -s /etc/sysconfig/i18n ]; then exit 0; fi

mkdir -p /etc/sysconfig
cat >> /etc/sysconfig/i18n << _EOF_
# mkimage-profiles live 20-locale hook
LANG=C.UTF-8
SUPPORTED=C.UTF-8
_EOF_

# set locale C.UTF-8 for root (needed for p10)
cat>/root/.i18n<<_EOF_
LANGUAGE=C.UTF-8
LANG=C.UTF-8
_EOF_

:
