#!/bin/sh

# m-p-d::profiles/rescue/image-scripts.d/999system
mv -f -- /etc/inittab.rescue /etc/inittab

# enable NFS mounts
if [ -x /etc/rc.d/init.d/rpcbind ]; then
	chkconfig rpcbind on
	sed -i 's,#\(RPCBIND_ARGS="-l".*\),\1,' /etc/sysconfig/rpcbind
fi

# remove unwanted startup scripts
find /etc/rc.d/rc{2,3,4,5}.d/ -type l -name 'S*' \
	-not -name '*logd' \
	-not -name '*network' \
	-not -name '*rpcbind' \
	-not -name '*random' \
	-not -name '*sysreport' \
	-not -name '*udev*' \
	-delete -print
