#!/bin/sh
# this breaks the default configuration on intent
# so that alterator-setup can run predictably

TARGET=/lib/systemd/system/$GLOBAL_OEM_TARGET.target

[ ! -s "$TARGET" ] ||
	ln -s "$TARGET" /etc/systemd/system/default.target

echo "LANG=en_US.utf-8" >> /etc/sysconfig/i18n

:
