#!/bin/sh -efu
# NB: initrd.mk carefully built by an earlier script

verbose() { [ -z "$GLOBAL_VERBOSE" ] || echo "** 81-make-initfs: $@" >&2; }

initrd="$(find /boot -type f -name 'initrd*.img' -print)"
if [ -n "$initrd" ]; then
	pdir="$(getconf LIBDIR)/propagator"
	mkdir -p "$pdir"
	for INITRD in $initrd; do
		KVER=${INITRD#*-}
		KVER=${KVER%.*}
		gzip < "$INITRD" > "$pdir"/initfs-"$KVER"
	done
else
	verbose '/boot/initrd*.img missing'
	exit 1
fi

if [ -h /boot/initrd.img ]; then
	KVER=$(readlink -ev /boot/initrd.img)
	KVER=${INITRD#*-}
	KVER=${KVER%.*}
	cp "$pdir"/initfs-$KVER "$pdir"/initfs
else
	verbose "/boot/initrd.img missing"
	cp "$pdir"/initfs-"$KVER" "$pdir"/initfs
	exit 1
fi
