#!/bin/sh
# * reset password for root
# * add user `altlinux' (without password)

GRPLIST="users scanner audio radio proc cdrom cdwriter wheel fuse netadmin"

verbose()
{
    if [ -n "$GLOBAL_VERBOSE" ]; then
        echo "HOOK: 30-users: $@"
    fi
}

add_user()
{
    verbose "Add $1 user"
    local groups=
    for g in $GRPLIST; do
	if groupmod $g 2>/dev/null; then
	    if [ -n "$groups" ]; then
		groups="$groups,$g"
	    else
		groups="$g"
	    fi
	fi
    done

    useradd -p "" -G "$groups" "$1" ||:
    # Workaround for ALT#13213
    chown -R "$1:auth" "/etc/tcb/$1"
    chown -R "$1:$1" /home/$1

    if [ -n "$GLOBAL_CRYPT_HOMES" ]; then
      verbose "Set password for user $1"
      echo "$1" | passwd --stdin $1
    fi

    sudoers="/etc/sudoers"
    if [ -w "$sudoers" ]; then
        verbose "Add $1 to sudoers."
        echo "$1   ALL=(root) NOPASSWD:ALL" >> "$sudoers"
    else
        verbose "Can't find writable $sudoers file."
    fi

    echo "Hello friend, say \`$1' to log in at \\l" >> /etc/issue
}

verbose "has started"

verbose "Clear password for root account"
usermod -p "" root

add_user altlinux

verbose "finished"
