#!/bin/sh
# Turn on xdg-user-dirs.
# NB: not yet available on t6/p6 hence the warning

. shell-config

if control xdg-user-dirs enabled; then
	shell_config_set /etc/xdg/user-dirs.defaults MOVIES 'Documents/Videos'
	shell_config_set /etc/xdg/user-dirs.defaults PHOTOS 'Documents/Pictures'
else
	echo "** warning: control xdg-user-dirs failed" >&2
fi
