#!/bin/sh
# unconditionally enable online repository

[ -n "$GLOBAL_LIVE_REPO" ] || exit 0

PROTO="${GLOBAL_LIVE_REPO%/*}"	# http, ftp, rsync
MIRROR="${GLOBAL_LIVE_REPO#*/}"	# alt, heanet, kiev, yandex, ...

sed -i "s,^#\(rpm \[.*\] ${PROTO:-http}.*\),\1," \
	"/etc/apt/sources.list.d/${MIRROR:-yandex}.list" ||:
