#!/bin/sh -efu

sed 's/Raspberry Pi 3 Model B+/Raspberry Pi 4/ ; s/boardflags3=0x48200100/boardflags3=0x44200100/' /lib/firmware/brcm/brcmfmac43455-sdio.raspberrypi,3-model-b-plus.txt > /lib/firmware/brcm/brcmfmac43455-sdio.txt
