#!/bin/sh

echo LXD configuration

# Setup subordinate ID's for root
usermod -v 1000000-1065535 -w 1000000-1065535 root

# Configuration of LXD
cat <<E_O_F >/etc/sysconfig/lxd-bridge
# The values below are defaults
USE_LXD_BRIDGE="true"
LXD_BRIDGE="lxdbr0"
LXD_CONFILE="/etc/lxd/dnsmasq.conf"
LXD_DOMAIN="lxd"

# IPv4
LXD_IPV4_ADDR="192.168.202.1"
LXD_IPV4_NETMASK="255.255.255.0"
LXD_IPV4_NETWORK="192.168.202.0/24"
LXD_IPV4_DHCP_RANGE="192.168.202.100,192.168.202.199"
LXD_IPV4_DHCP_MAX="100"
LXD_IPV4_NAT="true"

# IPv6
#LXD_IPV6_ADDR=""
#LXD_IPV6_MASK=""
#LXD_IPV6_NETWORK=""
#LXD_IPV6_NAT="false"
LXD_IPV6_PROXY="true"
E_O_F
