#!/bin/sh
# provide mkisofs with image contents sort order hints

### split over features or leave in a single piece?

# NB: only a single space/tab in between, no trailing whitespace
cat > /tmp/isosort <<__EOF__
ALTLinux 0
Metadata 100
altinst 700
rescue 800
live 900
syslinux 1000
__EOF__
