#!/bin/sh -efu
# setup settings for live user

livecd_user_conf=/etc/sysconfig/livecd-user.conf

[ -f "$livecd_user_conf" ] || exit 0

cat > /etc/sysconfig/livecd-user.conf << EOF
LIVECD_LOGIN="${GLOBAL_LIVE_USER:-}"
LIVECD_GROUPS="${GLOBAL_GROUPS:-}"
LIVECD_ADMIN=1
LIVECD_SUDO=1
EOF

[ -z "${GLOBAL_DEFAULT_SESSION:-}" ] ||
    echo "LIVECD_SESSION=$GLOBAL_DEFAULT_SESSION" >> "$livecd_user_conf"
