#!/bin/sh
# tweak xdg-user-dirs defaults if told so
# using tuples like "PHOTOS:Documents/Pictures"

. shell-config

CONFIG="/etc/xdg/user-dirs.defaults"

[ -z "$GLOBAL_XDG_USER_DIRS" ] ||
	echo "$GLOBAL_XDG_USER_DIRS" \
	| tr ' ' '\n' \
		| while IFS=':' read k v; do
			[ -n "$k" -a -n "$v" ] || continue
			shell_config_set "$CONFIG" "$k" "$v"
		done
