#!/bin/sh
# everything needed should have been done within initrd when this boots

rpm -e --nodeps apt libapt rpm librpmbuild librpm 2>/dev/null ||:
rm -rf /var/lib/apt /var/cache/apt /var/lib/rpm
rm -rf /lib/modules
rm -rf /usr/share
rm -rf /usr/lib*/{locale,perl*,python*,systemd,udev}
rm -rf /{etc,lib}/{firmware,udev}
