#!/bin/sh -efu
# save rpm and srpm lists

cd /.image
mkdir -p .disk/pkglists/stage1/{work,image}
cd .disk/pkglists/stage1/

rpm -qa --qf '%{name}-%{version}-%{release}.%{arch}.rpm\n' | sort -u > work/rpm.txt
rpm -qa --qf '%{sourcerpm}\n' | sort -u > work/srpm.txt
