#!/bin/sh

# FIXME: move somewhere else
#echo 'FEATURES += nfs' >> /etc/initrd.mk

# FIXME: move to plymouth feature
#if [ -f /etc/plymouth/plymouthd.conf ];then 
#    subst 's/#\([T\[]\)/\1/' /etc/plymouth/plymouthd.conf
#    echo 'FEATURES += plymouth' >> /etc/initrd.mk
#fi

