#!/bin/sh -efu

libdir="$(getconf LIBDIR)"

case "`arch`" in
	e2k)
		kname=image
		;;
	*)
		kname=vmlinuz
		;;
esac

kimage="$(find /boot -type f -name "$kname-*")"

rm -f /boot/full*.cz

for kver in $kimage; do
	kver="${kver#/boot/$kname-}"
	mkmodpack -p /.in/modules -o /tmp/modules-"$kver" -k "$kver"
	cat "$libdir/propagator/initfs" /tmp/modules-"$kver" > /boot/full-"$kver".cz

	sed \
		-e "s,@LIBDIR@,$libdir," \
		-e "s,@TMPDIR@,/tmp,g" \
		< "$WORKDIR/initfs" |
		gencpio - |
		gzip -c >> /boot/full-"$kver".cz

done
