#!/bin/sh
# symlink default kernel iff requested but not yet done

INSTALLER_KFLAVOUR="$INFO_INSTALLER_KFLAVOUR"
if [ -n "$GLOBAL_VERBOSE" ]; then
	echo "** INSTALLER_KFLAVOUR: $INSTALLER_KFLAVOUR"
fi

# kernel-image in instrumental chroot
VMLINK=/boot/vmlinuz

# better bail out early rather than make a silly symlink
shopt -s failglob

if [ -L "$VMLINK" ]; then
	echo "** $VMLINK -> $(readlink "$VMLINK")"
fi

if [ -n "$INSTALLER_KFLAVOUR" ]; then
	VMLINUZ="$(cd /boot; echo vmlinuz-*-$INSTALLER_KFLAVOUR-*)"
	if [ -n "$VMLINUZ" ]; then
		ln -sf "$VMLINUZ" "$VMLINK"
		echo "** overriding $VMLINK with $VMLINUZ"
	fi
fi
