#!/bin/sh -efux

TIME_UTC="${GLOBAL_TIME_UTC:-}"
in_zone="${GLOBAL_TIME_ZONE:-}"

. alterator-datetime-functions

if [ -n "$TIME_UTC" ]; then
    [ "$TIME_UTC" = 0 ] || TIME_UTC=1
    write_utc "$TIME_UTC"
fi

if [ -n "$in_zone" ]; then
    write_zone
fi
