#!/bin/sh
# by default hasher copy resolv.conf and /etc/hosts from host system
# we need to change it to useful defaults

echo 'nameserver 8.8.8.8' > /etc/resolv.conf
echo 'nameserver 8.8.4.4' > /etc/resolv.conf
#echo 'nameserver 2001:4860:4860::8888' > /etc/resolv.conf
#echo 'nameserver 2001:4860:4860::8844' > /etc/resolv.conf
echo '127.0.0.1 localhost.localdomain localhost' > /etc/hosts
